### PR TITLE
Path Mangle: Functionality to modify the path provided to allow and disallow

### LINKED ISSUE #3: The [path] value in allow & disallow directives must start with "/"
Settings `public: true` or `private: true` in a file's frontmatter add that page to the allow or disallow option without slash "/" in the beginning. Which lead to incorrect interpretation of its value by different crawler.

In Goolge [Robots.txt Specifications](https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt) you can find rule that [path] must start with "/".
Also with Yandex [Robots.txt analysis](https://webmaster.yandex.ru/tools/robotstxt/?ncrnd=1463) you can check that without "/" it marks such rule as error - "Rule doesn't start with / or *".

### PR DESCRIPTION
**Pull request by woodyrew**
Also:
- Updated tests
- Ignored and removed build directories
- Updated dependencies
- Updated Readme
- Fixes #3 

Needs **minor** version bump and publishing to npm.

### CODE REVIEW

**Comment by ghost** [comment]
Cool, thanks for the PR @woodyrew! Shall I just transfer this repo to you? I’m not planning on doing anything with it anymore.

**Comment by woodyrew** [comment]
Yes, no problem.

**Comment by ghost** [comment]
Cool, thanks. One thing though:

screen shot 2018-03-03 at 13 17 15

I merged your PR, so your fork can be safely deleted. Let me know when you have and I'll transfer the repo and the npm rights to you.

**Comment by woodyrew** [comment]
Deleted my fork. Will you transfer the rights for npm to publish also?

**Comment by ghost** [comment]
> Deleted my fork. Will you transfer the rights for npm to publish also?

Done. Also transferred via github, you should get a notification for the transfer request

**Pull request merged**
